### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by charleskawczynski** [scheinerman/FreeCell.jl#1]
Should we add docs (and deployment)? I'd be happy to help.

**Comment by scheinerman** [comment]
Hi Charles. Thanks for the kind offer. But this project, `FreeCell`, is just for me noodling around. It's not serious and it's not even working well. So it's not worth the time to invest for this (or code coverage). I can (more-or-less) code OK in Julia, but all these software engineering tools do have me mystified. I have no idea what "bors" or a lot of other things do. 

So investing your time in `FreeCell` is not a good use of your generous offer. If you are willing to show me the ropes, then I think a useful, but not too large, project (such as either my [Mods](https://github.com/scheinerman/Mods.jl) or [Multisets](https://github.com/scheinerman/Mods.jl)) would be beneficial not only to me, but potentially to users.

For [SimpleGraphs](https://github.com/scheinerman/SimpleGraphs.jl) I made a bunch of Wiki pages ... that was a ton of work.
